# Generated by Django 3.0.7 on 2020-08-09 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('居酒屋', '居酒屋'), ('カフェ', 'カフェ'), ('うなぎ', 'うなぎ'), ('ラーメン', 'ラーメン')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('名古屋市内', '名古屋市内'), ('一宮・犬山・瀬戸', '一宮・犬山・瀬戸'), ('知多・半田・中部国際空港', '知多・半田・中部国際空港'), ('豊田・岡崎・安城', '豊田・岡崎・安城'), ('豊橋・蒲郡・伊良湖', '豊橋・蒲郡・伊良湖')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=255)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Genre')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Location')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10)),
                ('sex', models.CharField(choices=[('男性', '男性'), ('女性', '女性')], max_length=2)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AddField(
            model_name='store',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.User'),
        ),
        migrations.AddField(
            model_name='picture',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Store'),
        ),
        migrations.AddField(
            model_name='comment',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Store'),
        ),
    ]
