# Generated by Django 3.0.7 on 2020-08-11 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20200811_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(choices=[('居酒屋', '居酒屋'), ('カフェ', 'カフェ'), ('うなぎ', 'うなぎ'), ('ラーメン', 'ラーメン'), ('観光スポット', '観光スポット')], max_length=10),
        ),
    ]
