# Generated by Django 3.0.7 on 2020-08-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20200811_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(choices=[('居酒屋', '居酒屋'), ('カフェ', 'カフェ'), ('うなぎ', 'うなぎ'), ('ラーメン', 'ラーメン')], max_length=5),
        ),
    ]
