# Generated by Django 3.0.7 on 2020-08-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20200811_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='comment',
            field=models.CharField(default=1111, max_length=300),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
