# Generated by Django 3.0.7 on 2020-08-11 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20200811_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(default='defo', upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='food.Store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='comment',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
